# Generated by Django 4.2.7 on 2024-05-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='scheduleevent',
            options={'ordering': ['created_at']},
        ),
    ]
