# Generated by Django 4.2.7 on 2024-05-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0037_poll_parent_alter_poll_poll_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollareastatement',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='pollareastatementsegment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='pollproposal',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='polltypeschedule',
            options={'ordering': ['created_at']},
        ),
    ]
