# Generated by Django 4.2.7 on 2024-05-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notificationobject_related_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationobject',
            options={'ordering': ['created_at']},
        ),
    ]
