# Generated by Django 4.2.7 on 2024-05-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0026_grouppermissions_poll_fast_forward'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='groupfolder',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='grouppermissions',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='groupthread',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='groupuserdelegatepool',
            options={'ordering': ['created_at']},
        ),
    ]
