# Generated by Django 4.2.7 on 2024-06-01 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0030_alter_group_direct_join_alter_group_public"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grouptags",
            options={"verbose_name_plural": "group tags"},
        ),
    ]
