# Generated by Django 4.2.7 on 2024-05-30 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0005_comment_attachments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentsection",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterField(
            model_name="comment",
            name="message",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="comment.comment",
                verbose_name="parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("attachments__isnull", False),
                    ("message__isnull", False),
                    _connector="OR",
                ),
                name="comment_data_check",
            ),
        ),
    ]
