# Generated by Django 4.2.7 on 2024-06-01 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0006_alter_comment_message_comment_comment_data_check"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentsection",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="comment.comment",
                verbose_name="parent",
            ),
        ),
    ]
