# Generated by Django 4.2.7 on 2024-05-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_messagechannelparticipant_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='messagechannel',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='messagechanneltopic',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='messagefilecollection',
            options={'ordering': ['created_at']},
        ),
    ]
